### PR TITLE
feat: add cuttlefish:conf_get/4, cuttlefish_mapping:to_map/1

### PR DESCRIPTION
**Pull request by 6293**

### CODE REVIEW

**Comment by 6293** [comment]
these 2 APIs would be enough for emqx to fetch information about config.

usecase:
```
Conf = cuttlefish_conf:file(PathToConf),
{_, Mappings0, _} = cuttlefish_schema:files([PathToSchema]),
Mappings = [cuttlefish_mapping:to_map(M) || M <- Mappings0],
SetValue = cuttlefish:conf_get("a.b", Conf, undefined, Mappings).
```

Mappings and SetValue are to be stored in ets.

**Comment by zmstone** [comment]
> these 2 APIs would be enough for emqx to fetch information about config.
> 
> usecase:
> 
> ```
> Conf = cuttlefish_conf:file(PathToConf),
> {_, Mappings0, _} = cuttlefish_schema:files([PathToSchema]),
> Mappings = cuttlefish_mapping:to_map(Mappings0),
> SetValue = cuttlefish:conf_get("a.b", Conf, undefined, Mappings).
> ```
> 
> Mappings and SetValues are to be stored in ets.

you mean this?

```
Mappings = [cuttlefish_mapping:to_map(M) || M <- Mappings0],
```



I am thinking, It's more than just set values to be cached, rather the matched mapping.
so it'd be better if we can expose the API like:

For configs:
```
Conf = cuttlefish_conf:file(PathToConf), % configs can be cached in ets together with file change time
```

For schema:

```
Schema = cuttlefish_schema:files([PathToSchema]), % same way to cache
Mapping = cuttlefish_schema:match("a.b", Schema), % this is a map() returned, and can be cached too with "a.b" as key
```
With this ^, we can quickly query config doc and default values when serving reset APIs.

For set value:

```
Mapping = get_mapping("a.b") % this call can make use of the schema cache
Default = maps:get(default_value, Mapping),
cuttlefish:conf_get("a.b", ConfLookupFun, Default), % this returns the set value, `ConfLookupFun` can be a cache lookup or proplists lookup.
```

**Comment by 6293** [comment]
yes, you are right. fixed

**Comment by zmstone** [comment]
I edited my reply in case you did not notice @z8674558

**Comment by 6293** [comment]
> I am thinking, It's more than just set values to be cached, rather the matched mapping.
so it'd be better if we can expose the API like:

added `conf_get_with`, `match`.

**Review by zmstone — APPROVED** [review]

**Pull request merged**
